// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_EthManageScreen_screen_init(void)
{
    ui_EthManageScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EthManageScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EthRecvText = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthRecvText, 1000);
    lv_obj_set_height(ui_EthRecvText, 300);
    lv_obj_set_x(ui_EthRecvText, 0);
    lv_obj_set_y(ui_EthRecvText, -200);
    lv_obj_set_align(ui_EthRecvText, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EthRecvText, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -465);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Protocol");

    ui_EthProtocolSelect = lv_dropdown_create(ui_EthManageScreen);
    lv_dropdown_set_options(ui_EthProtocolSelect, "TCPClient\nTCPServer\nUDP");
    lv_obj_set_width(ui_EthProtocolSelect, 336);
    lv_obj_set_height(ui_EthProtocolSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EthProtocolSelect, -224);
    lv_obj_set_y(ui_EthProtocolSelect, 0);
    lv_obj_set_align(ui_EthProtocolSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EthProtocolSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label6 = lv_label_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -465);
    lv_obj_set_y(ui_Label6, 80);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "RemoteIP");

    ui_EthRemoteIPText = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthRemoteIPText, 150);
    lv_obj_set_height(ui_EthRemoteIPText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EthRemoteIPText, -320);
    lv_obj_set_y(ui_EthRemoteIPText, 80);
    lv_obj_set_align(ui_EthRemoteIPText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_EthRemoteIPText, "Placeholder...");

    ui_Label18 = lv_label_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -465);
    lv_obj_set_y(ui_Label18, 160);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "LocalIP");

    ui_EthLocalIPText = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthLocalIPText, 150);
    lv_obj_set_height(ui_EthLocalIPText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EthLocalIPText, -320);
    lv_obj_set_y(ui_EthLocalIPText, 160);
    lv_obj_set_align(ui_EthLocalIPText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_EthLocalIPText, "Placeholder...");

    ui_EthRemotePortText = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthRemotePortText, 50);
    lv_obj_set_height(ui_EthRemotePortText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EthRemotePortText, -200);
    lv_obj_set_y(ui_EthRemotePortText, 80);
    lv_obj_set_align(ui_EthRemotePortText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_EthRemotePortText, "Port");

    ui_EthLocalPortText = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthLocalPortText, 50);
    lv_obj_set_height(ui_EthLocalPortText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EthLocalPortText, -200);
    lv_obj_set_y(ui_EthLocalPortText, 160);
    lv_obj_set_align(ui_EthLocalPortText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_EthLocalPortText, "Port");

    ui_EthConnectBtn = lv_btn_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthConnectBtn, 60);
    lv_obj_set_height(ui_EthConnectBtn, 50);
    lv_obj_set_x(ui_EthConnectBtn, -90);
    lv_obj_set_y(ui_EthConnectBtn, 80);
    lv_obj_set_align(ui_EthConnectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EthConnectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EthConnectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * ethConnectLabel = lv_label_create(ui_EthConnectBtn);
    lv_label_set_text(ethConnectLabel, "Connect");
    lv_obj_center(ethConnectLabel);

    ui_EthShutdownBtn = lv_btn_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthShutdownBtn, 60);
    lv_obj_set_height(ui_EthShutdownBtn, 50);
    lv_obj_set_x(ui_EthShutdownBtn, -90);
    lv_obj_set_y(ui_EthShutdownBtn, 160);
    lv_obj_set_align(ui_EthShutdownBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EthShutdownBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EthShutdownBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * ethShutdownLabel = lv_label_create(ui_EthShutdownBtn);
    lv_label_set_text(ethShutdownLabel, "Shutdown");
    lv_obj_center(ethShutdownLabel);

    ui_EthSendText = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthSendText, 400);
    lv_obj_set_height(ui_EthSendText, 200);
    lv_obj_set_x(ui_EthSendText, 170);
    lv_obj_set_y(ui_EthSendText, 86);
    lv_obj_set_align(ui_EthSendText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_EthSendText, "Placeholder...");

    ui_EthSendBtn = lv_btn_create(ui_EthManageScreen);
    lv_obj_set_width(ui_EthSendBtn, 100);
    lv_obj_set_height(ui_EthSendBtn, 200);
    lv_obj_set_x(ui_EthSendBtn, 443);
    lv_obj_set_y(ui_EthSendBtn, 80);
    lv_obj_set_align(ui_EthSendBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EthSendBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EthSendBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * ethSendLabel = lv_label_create(ui_EthSendBtn);
    lv_label_set_text(ethSendLabel, "Send");
    lv_obj_center(ethSendLabel);
    
    ui_EthKeyboard = lv_keyboard_create(ui_EthManageScreen);
    lv_obj_add_flag(ui_EthKeyboard, LV_OBJ_FLAG_HIDDEN);

    eth_widgets.recv_text = ui_EthRecvText;
    eth_widgets.protocol_select = ui_EthProtocolSelect;
    eth_widgets.r_ip_text = ui_EthRemoteIPText;
    eth_widgets.r_port_text = ui_EthRemotePortText;
    eth_widgets.l_ip_text = ui_EthLocalIPText;
    eth_widgets.l_port_text = ui_EthLocalPortText;
    eth_widgets.connect_btn = ui_EthConnectBtn;
    eth_widgets.shutdown_btn = ui_EthShutdownBtn;
    eth_widgets.send_text = ui_EthSendText;
    eth_widgets.send_btn = ui_SerialSendBtn;

    lv_obj_add_event_cb(ui_EthConnectBtn, ui_event_EthConnectBtn, LV_EVENT_ALL, &eth_widgets);
    lv_obj_add_event_cb(ui_EthShutdownBtn, ui_event_EthShutdownBtn, LV_EVENT_ALL, &eth_widgets);
    lv_obj_add_event_cb(ui_EthSendBtn, ui_event_EthSendBtn, LV_EVENT_ALL, &eth_widgets);

    lv_obj_add_event_cb(ui_EthRemoteIPText, ui_event_EthKeyboard, LV_EVENT_ALL, ui_EthKeyboard);
    lv_obj_add_event_cb(ui_EthRemotePortText, ui_event_EthKeyboard, LV_EVENT_ALL, ui_EthKeyboard);
    lv_obj_add_event_cb(ui_EthLocalIPText, ui_event_EthKeyboard, LV_EVENT_ALL, ui_EthKeyboard);
    lv_obj_add_event_cb(ui_EthLocalPortText, ui_event_EthKeyboard, LV_EVENT_ALL, ui_EthKeyboard);
    lv_obj_add_event_cb(ui_EthSendText, ui_event_EthKeyboard, LV_EVENT_ALL, ui_EthKeyboard);
}
