// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_EthManageScreen_screen_init(void)
{
    ui_EthManageScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EthManageScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea5 = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_TextArea5, 823);
    lv_obj_set_height(ui_TextArea5, 160);
    lv_obj_set_x(ui_TextArea5, -151);
    lv_obj_set_y(ui_TextArea5, -50);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");

    ui_Label3 = lv_label_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -526);
    lv_obj_set_y(ui_Label3, 85);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);

    ui_Dropdown1 = lv_dropdown_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Dropdown1, 361);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -285);
    lv_obj_set_y(ui_Dropdown1, 83);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label5 = lv_label_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -516);
    lv_obj_set_y(ui_Label5, 147);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);

    ui_TextArea6 = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_TextArea6, 150);
    lv_obj_set_height(ui_TextArea6, 45);
    lv_obj_set_x(ui_TextArea6, -405);
    lv_obj_set_y(ui_TextArea6, 146);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");

    ui_Label6 = lv_label_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -522);
    lv_obj_set_y(ui_Label6, 201);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);

    ui_TextArea7 = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_TextArea7, 150);
    lv_obj_set_height(ui_TextArea7, 47);
    lv_obj_set_x(ui_TextArea7, -402);
    lv_obj_set_y(ui_TextArea7, 206);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea7, "Placeholder...");

    ui_Button3 = lv_btn_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -268);
    lv_obj_set_y(ui_Button3, 144);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -265);
    lv_obj_set_y(ui_Button5, 205);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 90);
    lv_obj_set_x(ui_Button6, -138);
    lv_obj_set_y(ui_Button6, 172);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea8 = lv_textarea_create(ui_EthManageScreen);
    lv_obj_set_width(ui_TextArea8, 266);
    lv_obj_set_height(ui_TextArea8, 138);
    lv_obj_set_x(ui_TextArea8, 92);
    lv_obj_set_y(ui_TextArea8, 140);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea8, "Placeholder...");

    ui_Switch2 = lv_switch_create(ui_EthManageScreen);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -825);
    lv_obj_set_y(ui_Switch2, -253);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

}
