// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PeriManageScreen
void ui_PeriManageScreen_screen_init(void);
lv_obj_t * ui_PeriManageScreen;
lv_obj_t * ui_SerialSendTextArea;
lv_obj_t * ui_PortLabel;
lv_obj_t * ui_SerialPortSelect;
lv_obj_t * ui_Label2;
lv_obj_t * ui_SerialBaudrateSelect;
lv_obj_t * ui_SerialDatabitsSelect;
lv_obj_t * ui_SerialStopbitsSelect;
lv_obj_t * ui_SerialParitySelect;
lv_obj_t * ui_SerialFlowControlSelect;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
void ui_event_SerialOpenBtn(lv_event_t * e);
lv_obj_t * ui_SerialOpenBtn;
void ui_event_SerialSendBtn(lv_event_t * e);
lv_obj_t * ui_SerialSendBtn;
lv_obj_t * ui_SerialReadPanel;
void ui_event_WifiScanBtn(lv_event_t * e);
lv_obj_t * ui_WifiScanBtn;
void ui_event_WifiSwitch(lv_event_t * e);
lv_obj_t * ui_WifiSwitch;
lv_obj_t * ui_Label1;
lv_obj_t * ui_WifiSSIDSelect;
lv_obj_t * ui_WifiPasswordTextArea;
lv_obj_t * ui_WifiEncryptMethodSelect;
void ui_event_WifiConnectBtn(lv_event_t * e);
lv_obj_t * ui_WifiConnectBtn;
lv_obj_t * ui_Label11;
void ui_event_BacklightSlider(lv_event_t * e);
lv_obj_t * ui_BacklightSlider;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label10;
lv_obj_t * ui_BarttetyPercent;
lv_obj_t * ui_Label15;
lv_obj_t * ui_BatteryChagingStatus;
lv_obj_t * ui_SuspendBtn;
lv_obj_t * ui_PoweroffBtn;
lv_obj_t * ui_Label16;
lv_obj_t * ui_ADCValuePanel1;
lv_obj_t * ui_Label17;
lv_obj_t * ui_ADCValuePanel2;
lv_obj_t * ui_Label14;
lv_obj_t * ui_ADCValuePanel3;
lv_obj_t * ui_GPIOSelect;
lv_obj_t * ui_Label19;
lv_obj_t * ui_GPIODirectionSelect;
lv_obj_t * ui_Label20;
lv_obj_t * ui_GPIOValueSelect;
lv_obj_t * ui_Label21;

void ui_event_PeriKeyboard(lv_event_t * e);
lv_obj_t * ui_PeriKeyboard;

// SCREEN: ui_EthManageScreen
void ui_EthManageScreen_screen_init(void);
lv_obj_t * ui_EthManageScreen;
lv_obj_t * ui_EthRecvPanel;
lv_obj_t * ui_Label5;
lv_obj_t * ui_EthProtocolSelect;
lv_obj_t * ui_Label6;
lv_obj_t * ui_EthRemoteIPText;
lv_obj_t * ui_Label18;
lv_obj_t * ui_EthLocalIPText;
lv_obj_t * ui_EthRemotePortText;
lv_obj_t * ui_EthLocalPortText;
void ui_event_EthConnectBtn(lv_event_t * e);
lv_obj_t * ui_EthConnectBtn;
void ui_event_EthShutdownBtn(lv_event_t * e);
lv_obj_t * ui_EthShutdownBtn;
lv_obj_t * ui_EthSendText;
void ui_event_EthSendBtn(lv_event_t * e);
lv_obj_t * ui_EthSendBtn;
lv_obj_t * ui____initial_actions0;

void ui_event_EthKeyboard(lv_event_t * e);
lv_obj_t * ui_EthKeyboard;

void ui_event_EthRemoteIPText(lv_event_t * e);
void ui_event_EthRemotePortText(lv_event_t * e);
void ui_event_EthLocalIPText(lv_event_t * e);
void ui_event_EthLocalPortText(lv_event_t * e);
void ui_event_EthSendText(lv_event_t * e);

serial_widgets_t serial_widgets;
wifi_widgets_t wifi_widgets;
eth_widgets_t eth_widgets;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SerialOpenBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED)
        serial_open_clicked(e);
}

void ui_event_SerialSendBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED)
        serial_send_clicked(e);
}

void ui_event_PeriKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *keyboard = lv_event_get_user_data(e);

    if (event_code == LV_EVENT_FOCUSED) {
        lv_keyboard_set_textarea(keyboard, target);
        lv_obj_clear_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }

    if (event_code == LV_EVENT_DEFOCUSED)
    {
        lv_keyboard_set_textarea(keyboard, NULL);
        lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_event_BacklightSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_VALUE_CHANGED)
        backlight_value_changed(e);
}

void ui_event_WifiScanBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED)
        wifi_scan_clicked(e);
}

void ui_event_WifiConnectBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED)
        wifi_connect_clicked(e);
}

void ui_event_WifiSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_VALUE_CHANGED)
        wifi_switch_value_changed(e);
}

void ui_event_EthSendBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        eth_send_btn_clicked(e);
    }
}

void ui_event_EthConnectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        eth_connect_btn_clicked(e);
    }
}

void ui_event_EthShutdownBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        eth_shutdown_btn_clicked(e);
    }
}

void ui_event_EthKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *keyboard = lv_event_get_user_data(e);

    if (event_code == LV_EVENT_FOCUSED) {
        lv_keyboard_set_textarea(keyboard, target);
        lv_obj_clear_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }

    if (event_code == LV_EVENT_DEFOCUSED)
    {
        lv_keyboard_set_textarea(keyboard, NULL);
        lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PeriManageScreen_screen_init();
    ui_EthManageScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_EthManageScreen);
}
