// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_PeriManageScreen
void ui_PeriManageScreen_screen_init(void);
extern lv_obj_t * ui_PeriManageScreen;
void ui_event_SerialSendTextArea(lv_event_t * e);
extern lv_obj_t * ui_SerialSendTextArea;
extern lv_obj_t * ui_PortLabel;
extern lv_obj_t * ui_SerialPortSelect;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_SerialBaudrateSelect;
extern lv_obj_t * ui_SerialDatabitsSelect;
extern lv_obj_t * ui_SerialStopbitsSelect;
extern lv_obj_t * ui_SerialParitySelect;
extern lv_obj_t * ui_SerialFlowControlSelect;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event_SerialOpenBtn(lv_event_t * e);
extern lv_obj_t * ui_SerialOpenBtn;
void ui_event_SerialSendBtn(lv_event_t * e);
extern lv_obj_t * ui_SerialSendBtn;
extern lv_obj_t * ui_SerialReadPanel;
void ui_event_WifiScanBtn(lv_event_t * e);
extern lv_obj_t * ui_WifiScanBtn;
void ui_event_WifiSwitch(lv_event_t * e);
extern lv_obj_t * ui_WifiSwitch;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_WifiSSIDSelect;
extern lv_obj_t * ui_WifiPasswordTextArea;
extern lv_obj_t * ui_WifiEncryptMethodSelect;
void ui_event_WifiConnectBtn(lv_event_t * e);
extern lv_obj_t * ui_WifiConnectBtn;
extern lv_obj_t * ui_Label11;
void ui_event_BacklightSlider(lv_event_t * e);
extern lv_obj_t * ui_BacklightSlider;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BarttetyPercent;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_BatteryChagingStatus;
extern lv_obj_t * ui_SuspendBtn;
extern lv_obj_t * ui_PoweroffBtn;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_ADCValuePanel1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_ADCValuePanel2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_ADCValuePanel3;
extern lv_obj_t * ui_GPIOSelect;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_GPIODirectionSelect;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_GPIOValueSelect;
extern lv_obj_t * ui_Label21;
void ui_event_PeriKeyboard(lv_event_t * e);
extern lv_obj_t * ui_PeriKeyboard;
// SCREEN: ui_EthManageScreen
void ui_EthManageScreen_screen_init(void);
extern lv_obj_t * ui_EthManageScreen;
extern lv_obj_t * ui_EthRecvPanel;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_EthProtocolSelect;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_EthRemoteIPText;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_EthLocalIPText;
extern lv_obj_t * ui_EthRemotePortText;
extern lv_obj_t * ui_EthLocalPortText;
void ui_event_EthConnectBtn(lv_event_t * e);
extern lv_obj_t * ui_EthConnectBtn;
void ui_event_EthShutdownBtn(lv_event_t * e);
extern lv_obj_t * ui_EthShutdownBtn;
extern lv_obj_t * ui_EthSendText;
void ui_event_EthSendBtn(lv_event_t * e);
extern lv_obj_t * ui_EthSendBtn;
void ui_event_EthKeyboard(lv_event_t * e);
extern lv_obj_t * ui_EthKeyboard;
extern lv_obj_t * ui____initial_actions0;
void ui_event_EthKeyboard(lv_event_t * e);
extern lv_obj_t * ui_EthKeyboard;

extern serial_widgets_t serial_widgets;
extern wifi_widgets_t wifi_widgets;
extern eth_widgets_t eth_widgets;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
