// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SerialSendBtn
void ui_SerialSendBtn_screen_init(void);
extern lv_obj_t * ui_SerialSendBtn;
extern lv_obj_t * ui_SerialSendTextArea;
extern lv_obj_t * ui_PortLabel;
extern lv_obj_t * ui_SerialPortSelect;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_SerialBaudrateSelect;
extern lv_obj_t * ui_SerialDatabitsSelect;
extern lv_obj_t * ui_SerialStopbitsSelect;
extern lv_obj_t * ui_SerialParitySelect;
extern lv_obj_t * ui_SerialFlowControlSelect;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_SerialOpenBtn;
extern lv_obj_t * ui_SerialSendBt;
extern lv_obj_t * ui_SerialReadPanel;
extern lv_obj_t * ui_WifiScanBtn;
extern lv_obj_t * ui_WifiSwitch;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_WifiSSIDSelect;
extern lv_obj_t * ui_WifiPasswordTextArea;
extern lv_obj_t * ui_WifiEncryptMethodSelect;
extern lv_obj_t * ui_WifiConnectBtn;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_BacklightSlider;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BarttetyPercent;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_BatteryChagingStatus;
extern lv_obj_t * ui_SuspendBtn;
extern lv_obj_t * ui_PoweroffBtn;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_ADCValuePanel1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_ADCValuePanel2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_ADCValuePanel3;
extern lv_obj_t * ui_GPIOSelect;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_GPIODirectionSelect;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_GPIOValueSelect;
extern lv_obj_t * ui_Label21;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_TextArea8;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
