// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <termios.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>

#include "ui.h"

#define TCP_TEST

int tcp_create_and_connect(const char *ip_addr, int port)
{
    int ret;
    int fd;

    fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0)
    {
        perror("Socket create");
        return -1;
    }

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));

    addr.sin_addr.s_addr = inet_addr(ip_addr);
    addr.sin_port = htons(port);
    addr.sin_family = AF_INET;
    socklen_t len = sizeof(addr);

    if (connect(fd, (struct sockaddr *)&addr, len) < 0)
    {
        perror("connect failed");
        goto out_close_socket;
    }

    return fd;

out_close_socket:
    close(fd);
    return -1;
}

int tcp_create_and_listen(uint16_t port)
{
    int ret;
    int fd;

    fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0)
    {
        perror("Socket create");
        return -1;
    }

    struct sockaddr_in addr;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);

    if (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) < 0)
    {
        perror("bind");
        goto out_close_socket;
    }

    if (listen(fd, 5) < 0)
    {
        perror("listen");
        goto out_close_socket;
    }

    return fd;

out_close_socket:
    close(fd);

    return -1;
}

int tcp_write(int socket_fd, const char *w_buf, uint16_t buf_len)
{
    return write(socket_fd, w_buf, buf_len);
}

int tcp_read(int socket_fd, char *r_buf, uint16_t buf_len)
{
    return read(socket_fd, r_buf, buf_len);
}

int udp_create_socket(uint16_t my_port)
{
    int fd;

    fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (fd < 0)
    {
        perror("udp socket");
        return -1;
    }

    struct sockaddr_in my_addr;
    my_addr.sin_addr.s_addr = INADDR_ANY;
    my_addr.sin_port = htons(my_port);
    my_addr.sin_family = AF_INET;

    if (bind(fd, (struct sockaddr *)&my_addr, sizeof(my_addr)) < 0)
    {
        perror("udp bind");
        goto out_close_socket;
    }

    printf("%s %d\n", inet_ntoa(my_addr.sin_addr), ntohs(my_addr.sin_port));

    return fd;

out_close_socket:
    close(fd);

    return -1;
}

int udp_recv_from(int socket_fd, const char *ip_addr, uint16_t port, void *recv_buf, uint16_t buf_len)
{
    struct sockaddr_in from_addr;
    socklen_t len = sizeof(from_addr);

    from_addr.sin_addr.s_addr = inet_addr(ip_addr);
    from_addr.sin_port = htons(port);
    from_addr.sin_family = AF_INET;

    return recvfrom(socket_fd, recv_buf, buf_len, 0, (struct sockaddr *)&from_addr, &len);
}

int udp_send_to(int socket_fd, const char *ip_addr, uint16_t port, const void *send_buf, uint16_t buf_len)
{
    struct sockaddr_in to_addr;

    to_addr.sin_addr.s_addr = inet_addr(ip_addr);
    to_addr.sin_port = htons(port);
    to_addr.sin_family = AF_INET;

    return sendto(socket_fd, send_buf, buf_len, 0, (struct sockaddr *)&to_addr, sizeof(to_addr));
}


void serial_open_clicked(lv_event_t *e)
{
	int serial_fd;
	char port_name[64] = {0};
	char buf[128] = {0};
	serial_widgets_t *widgets = lv_event_get_user_data(e);
	struct termios new_settings, old_settings;

	lv_dropdown_get_selected_str(widgets->port_select, port_name, sizeof(port_name));

	serial_fd = open(port_name, O_RDWR | O_NOCTTY | O_NDELAY);
	if (serial_fd < 0)
	{
		LV_LOG_ERROR("Failed to open serial");
		return;
	}

	memset(&new_settings, 0, sizeof(new_settings));
	memset(&old_settings, 0, sizeof(old_settings));

	if (tcgetattr(serial_fd, &old_settings) < 0)
	{
		LV_LOG_ERROR("Failed to get serial attr\n");
		goto out_close_serial;
	}

	new_settings.c_cflag |= CLOCAL | CREAD;
	new_settings.c_cflag &= ~CSIZE;

	lv_dropdown_get_selected_str(widgets->baudrate_select, buf, sizeof(buf));
	uint32_t baudrate = strtoul(buf, NULL, 0);

	switch (baudrate)
	{
	case 1200:
		cfsetspeed(&new_settings, B1200);
		break;
	case 2400:
		cfsetspeed(&new_settings, B2400);
		break;
	case 4800:
		cfsetspeed(&new_settings, B4800);
		break;
	case 9600:
		cfsetspeed(&new_settings, B9600);
		break;
	case 19200:
		cfsetspeed(&new_settings, B19200);
		break;
	case 38400:
		cfsetspeed(&new_settings, B38400);
		break;
	case 57600:
		cfsetspeed(&new_settings, B57600);
		break;
	case 115200:
		cfsetspeed(&new_settings, B115200);
		break;
	case 230400:
		cfsetspeed(&new_settings, B230400);
		break;
	case 460800:
		cfsetspeed(&new_settings, B460800);
		break;
	case 921600:
		cfsetspeed(&new_settings, B921600);
		break;
	default:
		LV_LOG_ERROR("unsupported baudrate\n");
		goto out_close_serial;
	}

	memset(buf, 0, sizeof(buf));

	lv_dropdown_get_selected_str(widgets->databits_select, buf, sizeof(buf));
	uint32_t databits = strtoul(buf, NULL, 0);
	switch (databits)
	{
	case 5:
		new_settings.c_cflag |= CS5;
		break;
	case 6:
		new_settings.c_cflag |= CS6;
		break;
	case 7:
		new_settings.c_cflag |= CS7;
		break;
	case 8:
		new_settings.c_cflag |= CS8;
		break;
	default:
		LV_LOG_ERROR("unsupported databits\n");
		goto out_close_serial;
	}

	memset(buf, 0, sizeof(buf));

	lv_dropdown_get_selected_str(widgets->databits_select, buf, sizeof(buf));
	char parity = buf[0];
	switch (parity)
	{
	case 'N':
		new_settings.c_cflag &= ~PARENB; /* Clear parity enable */
		new_settings.c_iflag &= ~INPCK;	 /* Disable input parity check */
		break;
	case 'O':
		new_settings.c_cflag |= (PARODD | PARENB); /* Odd parity instead of even */
		new_settings.c_iflag |= INPCK;			   /* Enable input parity check */
		break;
	case 'E':
		new_settings.c_cflag |= PARENB;	 /* Enable parity */
		new_settings.c_cflag &= ~PARODD; /* Even parity instead of odd */
		new_settings.c_iflag |= INPCK;	 /* Enable input parity check */
		break;
	case 'M':
		new_settings.c_cflag |= PARENB; /* Enable parity */
		new_settings.c_cflag |= CMSPAR; /* Stick parity instead */
		new_settings.c_cflag |= PARODD; /* Even parity instead of odd */
		new_settings.c_iflag |= INPCK;	/* Enable input parity check */
		break;
	case 'S':
		new_settings.c_cflag |= PARENB;	 /* Enable parity */
		new_settings.c_cflag |= CMSPAR;	 /* Stick parity instead */
		new_settings.c_cflag &= ~PARODD; /* Even parity instead of odd */
		new_settings.c_iflag |= INPCK;	 /* Enable input parity check */
		break;
	default:
		LV_LOG_ERROR("unsupported parity\n");
		goto out_close_serial;
	}

	memset(buf, 0, sizeof(buf));
	lv_dropdown_get_selected_str(widgets->hardflow_select, buf, sizeof(buf));

	if (!strcmp(buf, "true"))
		new_settings.c_cflag |= CRTSCTS;
	else
		new_settings.c_cflag &= ~CRTSCTS;

	tcflush(serial_fd, TCIOFLUSH);

	if (tcsetattr(serial_fd, TCSANOW, &new_settings) != 0)
	{
		LV_LOG_ERROR("setattr failed\n");
		goto out_close_serial;
	}

	widgets->serial_fd = serial_fd;

	return;

out_close_serial:
	close(serial_fd);

	return;
}

void serial_send_clicked(lv_event_t *e)
{
	// Your code here
	serial_widgets_t *widgets = lv_event_get_user_data(e);

	// write(serial_widgets->serial_fd, )

	if (widgets->serial_fd > 0)
	{
		const char *buf = lv_textarea_get_text(widgets->send_text);
		write(widgets->serial_fd, buf, strlen(buf));
	}
	else
	{
		LV_LOG_WARN("Serial not connected\n");
	}
}

void backlight_value_changed(lv_event_t *e)
{
	lv_obj_t *slider = lv_event_get_target(e);
	lv_obj_t *label = lv_event_get_user_data(e);
	char buf[64];
	int32_t value = lv_slider_get_value(slider);
	lv_snprintf(buf, sizeof(buf), "%d%%", value);
	lv_label_set_text(label, buf);
	lv_obj_align_to(label, slider, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);

	lv_snprintf(buf, sizeof(buf), "echo %u > /sys/class/backlight/backlight/brightness", (uint32_t)0xff * value / 100);

	LV_LOG_WARN("execute %s\n", buf);

	// system(buf);
}

void wifi_scan_clicked(lv_event_t *e)
{
	uint16_t ssid_index = 0;
	char *p_n, *p_ssid_start, *p_ssid_end;
	FILE *fp;
	char buf[BUFSIZ] = {0}, ssid_buf[128] = {0};
	wifi_widgets_t *widgets = lv_event_get_user_data(e);

	if ((fp = popen("wpa_cli scan", "r")) == NULL)
	{
		LV_LOG_ERROR("Failed to scan wifi");
		return;
	}

	while (fgets(buf, sizeof(buf), fp) != NULL) // fgets()此处是否会阻塞？
	{
		if (strstr(buf, "Selected interface") != NULL)
			continue;

		if (strstr(buf, "OK") != NULL)
		{
			LV_LOG_ERROR("close fp and return\n");
			pclose(fp);
			return;
		}
	}

	pclose(fp);

	fp = popen("wpa_cli scan_r", "r");
	if (!fp)
	{
		LV_LOG_ERROR("Failed to get scan result\n");
		return;
	}

	memset(buf, 0, sizeof(buf));
	lv_dropdown_clear_options(widgets->ssid_select);

	while (fgets(buf, BUFSIZ, fp) != NULL)
	{
		if (strstr(buf, "bssid") != 0 || strstr(buf, "Selected interface") != 0)
			continue;

		if ((p_n = strstr(buf, "\n")) != NULL) // 注意，\n是接收到的最后一个字符
		{
			p_ssid_end = p_n - 1; //'\n前面一个字符'
			while (*p_n != '\t')  // 中间是用'\t'制表符隔开的
				p_n--;

			p_ssid_start = p_n; //'\t'
			strncpy(ssid_buf, (p_ssid_start + 1), (p_ssid_end - p_ssid_start));
		}

		// printf("ssid: %u -> %s\n", ssid_index - 1, ssid_buf[ssid_index - 1]);

		lv_dropdown_add_option(widgets->ssid_select, ssid_buf, ssid_index);
		ssid_index++;
	}

	pclose(fp);
}

void wifi_connect_clicked(lv_event_t *e)
{
	FILE *fp;
	const char *set_ssid = "wpa_cli -i wlan0 set_network 0 ssid ";
	const char *set_password = "wpa_cli -i wlan0 set_network 0 psk ";
	char buf[128] = {0};
	char *cmd = NULL;
	wifi_widgets_t *widgets = lv_event_get_user_data(e);

	cmd = (char *)malloc(sizeof(char) * 128);

	lv_dropdown_get_selected_str(widgets->ssid_select, buf, sizeof(buf));

	strcat(cmd, set_ssid);
	strcat(cmd, "'\"");
	strcat(cmd, buf);
	strcat(cmd, "\"'");
	LV_LOG_INFO("%s\n", cmd);

	if ((fp = popen(cmd, "r")) == NULL)
	{
		LV_LOG_ERROR("set ssid failed\n");
		return;
	}

	while (fgets(buf, sizeof(buf), fp) != NULL)
	{
		if (strstr(buf, "FAIL") != NULL)
		{
			LV_LOG_ERROR("Failed to set ssid\n");
			pclose(fp);
			return;
		}
	}
	pclose(fp);
	
	memset(buf, 0, sizeof(buf));
	memset(cmd, 0, sizeof(cmd));

	lv_dropdown_get_selected_str(widgets->password_text, buf, sizeof(buf));

	strcat(cmd, set_password);
	strcat(cmd, "'\"");
	strcat(cmd, buf);
	strcat(cmd, "\"'");
	LV_LOG_INFO("%s\n", cmd);

	if ((fp = popen(cmd, "r")) == NULL) {
		LV_LOG_ERROR("Set psk failed\b");
		return;
	}

	while (fgets(buf, sizeof(buf), fp) != NULL) {
		if (strstr(buf, "FAIL") != NULL) {
			LV_LOG_ERROR("Failed to set psk\n");
			pclose(fp);
			return;
		}
	}

	pclose(fp);

	free(cmd);

	return 0;
}

void wifi_switch_value_changed(lv_event_t *e)
{
	lv_obj_t *obj = lv_event_get_target(e);

	if (lv_obj_has_state(obj, LV_STATE_CHECKED))
		system("wpa_supplicant -Dnl80211 -iwlan0 -B -c /etc/wpa_supplicant.conf");
	else
		system("killall wpa_supplicant");
}

void eth_send_btn_clicked(lv_event_t * e)
{
	// Your code here
	lv_obj_t *obj = lv_event_get_target(e);
	eth_widgets_t *widgets = lv_event_get_user_data(e);


}

void eth_connect_btn_clicked(lv_event_t * e)
{
	lv_obj_t *obj = lv_event_get_target(e);
	eth_widgets_t *widgets = lv_event_get_user_data(e);

	
}

void eth_shutdown_btn_clicked(lv_event_t * e)
{
	
}